### ISSUE TITLE
新規画面登録時、トークンURLをクリックする前にログインするとエラーになる

### ISSUE THREAD

**Issue by nomuhito** [hirorosoft/Retiree#36]

**Comment by nomuhito** [comment]
新規会員登録のまちがいです。。

**Comment by hirorosoft** [comment]
どんなエラーになる？？

以下？？
ErrorException in bcc98b2f25c5faef595bda009291f5690980e789.php line 18:
Trying to get property of non-object (View: C:\xampp\htdocs\Retiree\resources\views\career1.blade.php) (View: C:\xampp\htdocs\Retiree\resources\views\career1.blade.php)

**Comment by nomuhito** [comment]
ステージング環境なのでwoopsしか。。
ローカルでは確認できてません。
前まで登録未完了のバリデーション走ってたと思います。

**Comment by nomuhito** [comment]
そう言えばそのログ、土曜の夜中にに「発生しない？」って聞いてきた奴とおなじじゃない？

**Comment by hirorosoft** [comment]
フレームワーク上の
以下のifの処理「remember」がないから？？

trait AuthenticatesUsers
        if (Auth::guard($this->getGuard())->attempt($credentials, $request->has('remember'))) {
            return $this->handleUserWasAuthenticated($request, $throttles);
        }

**Comment by hirorosoft** [comment]
public function login(Request $request)
をオーバーライドさせ、$request->has('remember'))
を走らせないように対応

**Comment by hirorosoft** [comment]
＞＞そう言えばそのログ、土曜の夜中にに「発生しない？」って聞いてきた奴とおなじじゃない？
そうそう。同じ。。なぜVIEWのエラーがでるか不明
