### ISSUE TITLE
管理者ログインでログインすると、普通のログイン画面へ遷移する場合がある。

### ISSUE THREAD

**Issue by hirorosoft** [hirorosoft/Retiree#38]

**Comment by hirorosoft** [comment]
管理者、ユーザのsession関連？

**Comment by nomuhito** [comment]
この思いも寄らない画面に移動するときって、その前にエラーはいたり、戻るボタン使ってやり直した覚えとかない？
おれも別の画面で起きたりするからそういう感じのキャッシュクリアー的な奴のような。。

**Comment by hirorosoft** [comment]
あ、それはあるかも？？
