### ISSUE TITLE
メール連携機能の見直し

### ISSUE THREAD

**Issue by nomuhito** [hirorosoft/Retiree#40]
メール連携機能の見直しを行いました。実装済みテスト中
◎ユーザ宛てメールの見直し
・新規登録完了時（文言）
・パスワード変更時（文言）
・退会時（文言及び通知していなかったバグ）

◎管理者宛てメールの見直し
・新規登録完了時（通知していなかったバグ）
・キャリア情報入力完了時
・退会時

**Comment by hirorosoft** [comment]
ご要望フォーム、お問い合わせフォーム
のメールは管理者のみでOK??

送信した本人には送ってないけど

**Comment by nomuhito** [comment]
問い合わせをたまわりました。みたいなやつ？
それもらった資料みてみるわ。質問したらそうしてっていわれそうやな。

**Comment by hirorosoft** [comment]
そそ。

**Comment by nomuhito** [comment]
送信者本人へのメールは不要との事です。
