### ISSUE TITLE
パスワード変更時のメールのFROMが「Example」

### ISSUE THREAD

**Issue by hirorosoft** [hirorosoft/Retiree#45]

**Comment by nomuhito** [comment]
メール差出人の取得元を考える必要がある。
新規登録、パスワード変更、退会の３つ
adminテーブル上は、gmailを保持しないが、
差出人はgmailにしたい。

**Comment by hirorosoft** [comment]
設定ファイルに持つか

**Comment by nomuhito** [comment]
設定ファイルか、adminテーブルの１レコード目や特定のレコードをメール送信用レコードにするか。

**Comment by hirorosoft** [comment]
対応完了
