### ISSUE TITLE
キャリア入力完了ボタン押したら管理者にメール飛ばす。

### ISSUE THREAD

**Issue by hirorosoft** [hirorosoft/Retiree#6]

**Comment by nomuhito** [comment]
他のソースを参考にメール送信まで実装したが、HTMLエスケープ処理が行われない。

**Comment by hirorosoft** [comment]
わかった。ファイル名がチガウ。xxx.blade.phpが正解。
ララベルの場合、こうしないとブレードテンプレート使用できない

**Comment by nomuhito** [comment]
view名をcompletion.blade.phpに修正動作確認済み。
